In [1]:
import numpy as np


In [2]:
tmp = np.array([1, 2, 3, -2, -1])

print(np.sign(tmp))

[ 1  1  1 -1 -1]


In [3]:
postion = np.where(tmp > 0)
postion

(array([0, 1, 2]),)

In [4]:
tmp[postion]

array([1, 2, 3])

In [9]:
exp = np.exp(tmp)
sum = sum(exp)
p = exp / sum
p

array([0.08855466, 0.24071653, 0.65433536, 0.00440888, 0.01198457])

In [10]:
tmp > 0

array([ True,  True,  True, False, False])

In [11]:
dout = np.array([1, 2, 3, 4, 5])

dout * (tmp > 0)

array([1, 2, 3, 0, 0])